### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by sina-log** [f-lab-edu/kid-safer#2]
- 로그인, 로그아웃을 할 수 있다.
- 메인 페이지를 빼 놓고 로그인을 체크하여 로그인 페이지로 이동 한다.
- 일정 시간이 지나면 자동 로그인 유지가 풀린다.

**Comment by oksusutea** [comment]
- [x] MyBatis 설정 및 MySql과 연동하기
- [x] USER DB 설계
- [x] UserDTO 작성
- [x] Login 관련 컨트롤러 및 서비스 추가
- [x] 예외처리 로직 적용

**Comment by oksusutea** [comment]
추가 적용 가능 사항 : 

- [x] 회원가입 후, 이메일 인증 받지 못했을 때 예외처리 로직 추가
- [ ] 로그인 관련 인터셉터 기능 개발
