### ISSUE TITLE
Child

### ISSUE THREAD

**Issue by sina-log** [f-lab-edu/kid-safer#4]
- 아이정보는 보호자가 등록할 수 있으며, 여러 아이를 등록 할 수 있다.
- 한 명의 아이는 한 명의 보호자에게만 등록 가능하다
- 아이의 성별, 나이, 학교, 특이사항 정보가 담겨져 있다.

**Comment by oksusutea** [comment]
- [x] 아이 테이블 설계
- [x] 아이 등록/수정/삭제/조회 기능 개발
