### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by sina-log** [f-lab-edu/kid-safer#5]
- 등원 요청시 게시 마감일, 시작일, 종료일, 지역, 시작시간, 종료시간, 비용, 코멘트 입력 가능
- 보호자는 게시마감이 지나면 신청자 중 한 명을 선택 가능
- 같은 주거지역, 겹치는 일정이 없는 사람 만 신청 가능

**Comment by oksusutea** [comment]
우선 부모(보호자)가 등원 도우미를 요청하는 게시글을 등록/수정/삭제하는 기능만 적용한다(추후 선택하는 기능 추가 적용)

* 요청 게시글에 대한 도메인 및 DTO 설계
* 서비스단 정의
* 비즈니스 예외 로직 설계
